[book]
authors = ["Sergey Mechtaev"]
language = "en"
multilingual = false
src = "src"
title = "Modus Documentation"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/modus-continens/modus"