name: Build website
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install mdbook
      - run: mdbook build
      - run: echo docs.modus-continens.com > book/CNAME
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        with:
          branch: gh-pages
          folder: book
